kurtmckee/feedparser

feedparser/namespaces/georss.py

added `from __future__ import generator_stop` to georss.py to make compatible with Python 3.7

Added import to georss.py to fix StopIteration error

---

.gitignore

The title is self-explanatory.

Ignore documentation build directory

---

CONTRIBUTORS.rst
NEWS
docs/introduction.rst
docs/version-detection.rst
feedparser/api.py
feedparser/encodings.py
feedparser/parsers/json.py
tests/json/example.json
tests/runtests.py

Add support for JSON feeds

---

.github/workflows/feedparser.yml
.gitignore
CONTRIBUTORS.rst
changelog.d/20210801_133300_palfrey_typing.rst
feedparser/api.py
feedparser/datetimes/__init__.py
feedparser/datetimes/iso8601.py
feedparser/datetimes/perforce.py
feedparser/encodings.py
feedparser/mixin.py
feedparser/sgml.py
pyproject.toml

Add typing support

---

.github/workflows/feedparser.yml
.pre-commit-config.yaml
changelog.d/20230219_143414_kurtmckee_update_python_support.rst
docs/introduction.rst
feedparser/namespaces/georss.py
pyproject.toml
tox.ini

Python support
--------------
*   Support Python 3.11.
*   Drop support for Python 3.6.

Update Python support

---

.readthedocs.yaml
changelog.d/20230219_170632_kurtmckee_fix_rtd.rst

Stewardship
-----------
*   Add a Read the Docs configuration.

Add a configuration for Read the Docs

---

.pre-commit-config.yaml
changelog.d/20230320_223906_kurtmckee_use_flake8.rst
feedparser/__init__.py
feedparser/api.py
feedparser/datetimes/greek.py
feedparser/encodings.py
feedparser/html.py
feedparser/http.py
feedparser/mixin.py
feedparser/namespaces/cc.py
tests/conftest.py
tests/test_encoding.py
tests/test_lxml_bug.py
tests/test_parse_parameters.py
tests/test_temporary_behavior.py
tox.ini

Exactly what it says on the tin.

Use flake8 for linting; fix identified issues

---

.gitignore
changelog.d/20230321_210848_kurtmckee_use_coverage.rst
pyproject.toml
tox.ini

Exactly what it says on the tin.

Track code coverage when running the test suite

---

changelog.d/20230322_230413_kurtmckee_update_doc_builds.rst
docs/add_custom_css.py
docs/conf.py
tox.ini

Project development
-------------------
*   Test doc builds against the same theme used on ReadTheDocs.

Update doc builds

---

tests/conftest.py

This doesn't result in a significant performance gain, but it's the right thing to do.

Reduce filesystem I/O in the test suite HTTP server

---

tests/helpers.py
tests/test_parse_parameters.py

This only affects code in the test suite.

Improve coverage

---

requirements/docs.txt
requirements/mypy.txt
requirements/pip-tools.txt

Exactly what it says on the tin.

Update pinned requirements (doc builds and mypy linting)

---

changelog.d/20230413_090924_kurtmckee_fix_json_parsing.rst
feedparser/api.py
feedparser/encodings.py
feedparser/sanitizer.py
tests/test_json.py
tox.ini

Fixed
-----
*   Fix a bug that prevented JSON feeds from being parsed.
A comparison was failing due to incompatible types,
which allowed XML declarations to be added to JSON feeds.
*   Fallback to JSON feed parsing if the XML parsers completely fail.

Fix JSON feed parsing

---

.github/workflows/feedparser.yml
.pre-commit-config.yaml
changelog.d/20230511_103746_kurtmckee_drop_python_3_7.rst
docs/introduction.rst
pyproject.toml
tox.ini

Python support
--------------
*   Drop support for Python 3.7.

Drop support for Python 3.7

---

.pre-commit-config.yaml
changelog.d/20230605_203701_kurtmckee_check_json_schema.rst

Exactly what it says on the tin.

Use check-jsonschema to validate the schema of config files

---

docs/introduction.rst

Remove an old Python 2 Unicode tutorial link

---

requirements/docs.txt
requirements/mypy.txt
requirements/pip-tools.txt

Exactly what it says on the tin. Fixes #386, too.

Update requirements files

---

.github/workflows/feedparser.yml

Use hashes as GitHub action identifiers, which is a best practice.
Dependabot has the ability to update hashes together with the tag name in trailing comments.
The following code was run to generate these changes:
```python
import pathlib
import re
actions = {
"actions/cache": ("704facf57e6136b1bc63b828d79edcd491f0ee84", "v3.3.2"),
"actions/checkout": ("8ade135a41bc03ea155e62e844d188df1ea18608", "v4.1.0"),
"actions/download-artifact": ("9bc31d5ccc31df68ecc42ccf4149144866c47d8a", "v3.0.2"),
"actions/setup-python": ("65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236", "v4.7.1"),
"actions/upload-artifact": ("a8a3f3ad30e3422c9c7b888a15615d19a852ae32", "v3.1.3"),
"aws-actions/amazon-ecr-login": ("062b18b96a7aff071d4dc91bc00c4c1a7945b076", "v2.0.1"),
"aws-actions/configure-aws-credentials": …
```

Use hashes as GitHub action identifiers

---

.github/workflows/feedparser.yml
changelog.d/20231210_103718_kurtmckee_python_support.rst
feedparser/__init__.py
pyproject.toml
tox.ini

Python support
--------------
*   Support Python 3.12.
*   Test against Python 3.13 pre-releases.

Support Python 3.12

---

feedparser/api.py
feedparser/html.py
feedparser/mixin.py
feedparser/namespaces/georss.py
feedparser/util.py

Remove unnecessary `elif` and `else` conditionals

---

changelog.d/20250622_121444_kurtmckee_rename_branches.rst

Project development
-------------------
*   Rename the ``develop`` branch to ``main``,
and rename the ``master`` branch to ``releases``.
To update local branches, run these commands
(assuming that the upstream repository is named "origin"):
```bash
git fetch origin
git branch -m develop main
git branch -u origin/main main
git branch -m master releases
git branch -u origin/releases releases
git remote set-head origin -a
```

Document the branch name changes
