kurtmckee/feedparser

feedparser/datetimes/rfc822.py

See #44 
This makes some speed improvements on datetimes.

define global var + remove set() [slow]

---

CONTRIBUTORS.rst
setup.cfg
setup.py

Use a [platform specific dependency](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies) to pull in libsgml3k on Python 3 in a way that will generate proper wheel metadata. With these changes a universal wheel is built that depends on sgmllib3k only on Python 3:
```
$ python setup.py bdist_wheel
running bdist_wheel
[...]
creating build/bdist.linux-x86_64/wheel/feedparser-5.2.1.dist-info/WHEEL
$ ls dist/
feedparser-5.2.1-py2.py3-none-any.whl
$ cd dist/
$ virtualenv --python=python2.7 env2
Already using interpreter /usr/bin/python2.7
New python executable in /home/twm/feedparser/dist/env2/bin/python2.7
Also creating executable in /home/twm/feedparser/dist/env2/bin/python
Installing setuptools, pip, wheel...done.
$ env2/bin/pip install …
```

Fix Python 3 conditional dependency specification

---

feedparser/encodings.py

I think that it is good to use cchardet. For instance, [aiohttp](http://aiohttp.readthedocs.io/en/stable/) are doing in the same way.

Change to use cchardet prior to chardet when the package installed

---

NEWS
docs/html-sanitization.rst
docs/resolving-relative-links.rst
feedparser/__init__.py
feedparser/api.py
feedparser/mixin.py
tests/runtests.py

The relocation of `feedparser.SANITIZE_HTML` to `feedparser.api.SANITIZE_HTML` made it really awkward to override. Because the flag is copied into `feedparser.mixin`, one would have to patch it there after importing `feedparser.api`, e.g.,:
```python
import feedparser.api
feedparser.mixin.SANITIZE_HTML = False
```
This PR restores the functionality of setting `feedparser.USER_AGENT`, `feedparser.SANITIZE_HTML`, and `feedparser.RESOLVE_RELATIVE_URIS`. Because assigning to global constants is a pretty awkward API, it also adds `feedparser.parse(sanitize_html=bool, resolve_relative_uris=bool)` arguments.
Unit tests and documentation updates are included.

Unbreak feedparser.SANITIZE_HTML

---

docs/changes-early.rst
docs/html-sanitization.rst
docs/version-detection.rst

There are a few more in the annotated examples and NEWS file, but the links aren't important for the examples, and I wasn't sure if modifying the older items in the changelog might break something that expects them to stay the same.

Replace dead links to diveintomark.org

---

feedparser/namespaces/georss.py
tox.ini

- Change _gen_georss_coords to capture StopIteration
from value list, using pattern from PEP
Fixes #130

Fix error with Python3.7 now PEP479 is enforced.

---

feedparser/datetimes/greek.py
feedparser/datetimes/hungarian.py
feedparser/datetimes/korean.py
feedparser/encodings.py
feedparser/html.py
feedparser/mixin.py
feedparser/sanitizer.py
feedparser/sgml.py

Just add a "r" prefix to some strings to remove the  "DeprecationWarning: invalid escape sequence" warnings that appear in Python 3.6.

Remove "DeprecationWarning: invalid escape sequence" in Python 3.6.

---

feedparser/encodings.py

Accessing Callable from collections is deprecated (should be from
collections.abc), but simply calling callable works here.

Use callable instead of isinstance Callable

---

.travis.yml
tox.ini

This PR adds a simple Travis CI configuration file that includes tox build configs for
* Python 2.7
* Python 3.4
* Python 3.5
* Python 3.6
* Python 3.7
Of course, at this point in time, only the first 4 variants will run successfully, the Python 3.7 tox build will fail until https://github.com/kurtmckee/feedparser/pull/131 is merged.
Once merged, please sign up for an account at https://travis-ci.org/, link your GitHub account, add this repository, and Travis CI will automatically build the project at each commit.

Travis support for automated builds including Python 3.7

---

feedparser/datetimes/__init__.py

According to the [documentation](https://pythonhosted.org/feedparser/date-parsing.html) if a 3rd party date handler raises any exception, `feedparser` should silently ignore it, and try other registered date handlers.  Coincidently, a feed that I've been working with uses the same date format as the 3rd party handler in the example on that page,  the `AttributeError` that is raised if a match is not found is not ignored.  All tests pass after having made the change, though I do not have python 3.4, 3.5 or 3.7 installed in order to test using them.
Finally, please let me express my gratitude for writing / maintaining this library, it's been great to use and forms the heart of one of my side-projects.

Catch `AttributeError` in `_parse_date`

---

feedparser/http.py
feedparser/mixin.py

Use encodebytes instead of encodestring in Python 3.9.

---

feedparser/namespaces/itunes.py

according to Apple's guide,  for <itunes:block>, only Yes is accepted
https://help.apple.com/itc/podcasts_connect/?lang=en#/itcb54353390
> Specifying the <itunes:block> tag with a Yes value, prevents the entire podcast from appearing in Apple Podcasts.
Specifying any value other than Yes has no effect.

support 'Yes' for itunes:block

---

setup.py

The current 6.0.0 version, which is Python 3 only, actually gets into Python 2 installations because of a missing `python_requires` in the setup.py. This PR specifies supporting Python 3.6 and above explicitly.

Add python_requires to avoid breaking unpinned Python 2 installs

---

docs/conf.py

I guess, it was only a misplaced parenthesis (#232)

Update regex expression to extract version, fixes #232

---

CONTRIBUTORS.rst
changelog.d/20210731_204227_6032823+jack1142_patch_1.rst
feedparser/util.py

This ensures that the warning is shown for the code that is actually the reason for the deprecation warning rather than having the warning show on feedparser's own code. This also makes it easier to suppress the deprecation warning correctly for the code that already has proper handling while not suppressing it on the code that is possibly prone to the issue.

Fix stack level for deprecation warnings

---

.github/workflows/feedparser.yml

Looks like this will work fine. We're testing 3.10 and thought we'd bring feedparser along for the ride.

add test support 3.10

---

pyproject.toml

Running the test suite, that the envs would show up as `py39-` really bothered me, this fixes that issue by making the dash part of the chardet generation.
Also adds 3.10 support while at it.
And there's something else I noticed: currently the test suite requires a global `sphinx` installed in order to run the "docs" env, is there a strong reason for that?

Add 3.10 and improve env-without-chardet

---

feedparser/mixin.py
feedparser/namespaces/_base.py
tests/wellformed/atom10/entry_content_and_summary.xml

This fixes #59. It is merely a rebase (with some variable renaming) of @mosasiru's original pull request (PR #60) which was never merged for some reason so that it doesn't conflict with the current develop branch.

Atom: Populate <summary> correctly if it comes after <content>

---

docs/introduction.rst

While reading the introduction docs, I got a bit confused because the info about the example for parsing a feed from a local file assuming the user is on windows is underneath the heading for parsing a feed from a remote URL.
I think moving it below the subheading it is about makes the docs easier to read

Move info about OS specific file syntax to correct subheading

---

.github/workflows/feedparser.yml

This should reduce double runs of CI when pushing branches like this one. BUT, I still want CI to run whenever anything merges to important branches!

Only run CI when merging ("pushing") to important branches

---

feedparser/html.py

This is a common mistake, see https://github.com/python/cpython/issues/99918#issuecomment-1333382582

Fix incorrect passing of flags to re.sub

---

feedparser/datetimes/rfc822.py
tests/test_date_parsers.py

```
Example: 'Fri,24 Nov 2023 18:28:36 -0000'
~~~~^~~ No space
```

datetimes/rfc822: support non-standard format

---

docs/http-useragent.rst

Updates the user-agent doc to include the current URL used in the default user-agent string: #458

Update http-useragent.rst with the correct user-agent string

---

feedparser/encodings.py
tests/test_encoding_helpers.py

read(-1) should not include the part of prefix that was returned before.

Fix a bug in PrefixFileWrapper

---

.github/workflows/test.yaml
changelog.d/20241208_112335_kurtmckee_rm_pypy_3_9.rst
tox.ini

PyPy 3.9 support was not yet released, so this manifests only as "Support PyPy 3.10".
Python support
--------------
*   Support PyPy 3.10.

Drop support for PyPy 3.9

---

docs/http-etag.rst

The docs still reference the older extra_headers on https://pythonhosted.org/feedparser/http-etag.html.

Reference `request_headers` parameter in docs instead of extra_headers.
